name: mini_blog
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  flutter_bloc: ^8.1.6
  http: ^1.2.2
  xml: ^6.5.0
  intl: ^0.20.1
  flutter_html: ^3.0.0-beta.2
  shared_preferences: ^2.3.3
  flutter_riverpod: ^2.6.1
  icons_launcher: ^3.0.0
  
   
icons_launcher:
  image_path: 'assets/icon/icon.png'
  platforms:
    android:
      enable: true
    ios:
      enable: false

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/icon/icon.png

  
